### ISSUE TITLE
node_modules\node-sass: Command failed.

### ISSUE THREAD

**Issue by michaelsomera** [ZhangMYihua/graphql-lesson#11]
error C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Admin\\Desktop\\React_VSG\\graphql-crwn-clothing\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python38\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\Desktop\\React_VSG\\graphql-crwn-clothing\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Admin\Desktop\React_VSG\graphql-crwn-clothing\node_modules\node-sass
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by superman566** [comment]
It looks like need to update react and rest libs to the latest version. 
`"dependencies": {
    "firebase": "^8.7.1",
    "node-sass": "^6.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-stripe-checkout": "^2.6.3",
    "redux": "^4.1.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "reselect": "^4.0.0"
  },`
